#!/bin/bash

# Construct the classpath

CLASSPATH=$(ls -1 lib/*.jar | paste -sd ":" -):warehouse-1.0-SNAPSHOT.jar

# Debugging port
PORT=4747
if [[ -v DEBUG ]]; then
    DEBUG_ARGS=-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=$PORT
else
    DEBUG_ARGS=""
fi
    
# exec java -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=$PORT  -classpath $CLASSPATH edu.mayo.genomics.CreateSchema
exec java $JVM_ARGS $DEBUG_ARGS -classpath $CLASSPATH edu.mayo.genomics.LoadVCF "$@"
